{{- range .Values.operators }}
{{- if eq .installPlanApproval "Manual" }}
---
# create one installplan-complete-verifier job per manual operator
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-%s" .csv "verifier" | trunc -63 | trimAll "-" }}
  namespace: {{ .namespace | default $.Release.Namespace }}
  labels:
    {{- include "operators-installer.labels" $ | nindent 4 }}
  annotations:
    {{- if $.Values.approveManualInstallPlanViaHook }}
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "30"
    {{- else }}
    argocd.argoproj.io/sync-wave: "-10"
    {{- end }}
spec:
  completions: 1
  parallelism: 1
  backoffLimit: {{ .installPlanVerifierRetries | default 10 }}
  activeDeadlineSeconds: {{ .installPlanVerifierActiveDeadlineSeconds | default 240 }}
  template:
    spec:
      containers:
      - name: installplan-complete-verifier
        image: {{ $.Values.installPlanApproverAndVerifyJobsImage }}
        command: ["/bin/sh","-c"]
        args:
          - >-
              python3 -m venv /tmp/venv &&
              source /tmp/venv/bin/activate &&
              pip3 install openshift-client &&
              python3 /scripts/installplan-verifier.py
        imagePullPolicy: Always
        env:
        - name: SUBSCRIPTION_CSV
          value: {{ .csv }}
        - name: SUBSCRIPTION
          value: {{ .name }}
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: installplan-approver-scripts
          mountPath: /scripts
      volumes:
      - name: installplan-approver-scripts
        configMap:
          name: installplan-approver-scripts
          defaultMode: 0777
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: {{ include "operators-installer.approverName" . }}
      serviceAccountName: {{ include "operators-installer.approverName" . }}
      terminationGracePeriodSeconds: 30
{{- end }}
{{- end }}