name: Validate

on: 
  push:
    paths-ignore:
      - '.github/**'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.github/**'
      - 'README.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  conftest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Conftest
        uses: redhat-cop/github-actions/confbatstest@e4729075dcd3f34946b80df6b1bfb952b9fee166 # v4
        with:
          tests: _test/conftest.sh
